dist: xenial
language: python
python:
  - "3.6"
  - "3.7"
  - "3.8"
install:
  - make dev
  - pip install codecov
script:
  - make test
  - codecov
notifications:
  email:
    on_success: never
    on_failure: always
